version: '3.8'

services:
  practicum:
    container_name: practicum_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - ./jupyter:/root/.jupyter
    environment:
        POSTGRES_USER: practicum
        POSTGRES_PASSWORD: toor
        POSTGRES_DB: practicum
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "pip install jupyter_contrib_nbextensions jupyter_nbextensions_configurator && jupyter nbextensions_configurator enable --user && jupyter contrib nbextension install --user && jupyter nbextension enable toc2/main && jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"]
    command: []

  postgres:
    image: postgres:latest
    container_name: practicum_postgres
    environment:
      POSTGRES_USER: practicum
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: practicum
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: